[language-server.nimlsp]
command = "nimlangserver"

[language-server.vlang]
command = "/home/licorice/.config/v-analyzer/bin/v-analyzer"
args = ["--stdio"]

[[language]]
name = "nim"
scope = "source.nim"
injection-regex = "nim"
file-types = ["nim","nims","nimble"]
shebangs = ["nim"]
roots = []
comment-token = "#"
language-servers = ["nimlsp"]
indent = { tab-width = 2, unit = " " }

[[language]]
name = "v"
scope = "source.nim"
injection-regex = "nim"
file-types = ["v","vsh","mod"]
comment-token = "//"
language-servers = ["vlang"]
indent = { tab-width = 4, unit = " " }

[[grammar]]
name = "nim"
source = { git = "https://github.com/alaviss/tree-sitter-nim" }
